# Generated by Django 3.2.4 on 2021-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('number', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
